# Generated by Django 2.1 on 2019-09-15 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_text', models.CharField(choices=[('Freshers', 'Freshers'), ('Growth', 'Growth'), ('Evolution', 'Evolution'), ('Reader', 'Reader')], max_length=20)),
                ('employment_text', models.CharField(choices=[('Regular', 'Regular'), ('Part-time', 'Part-time'), ('Group', 'Group')], max_length=10)),
                ('prizewinner_text', models.CharField(max_length=20)),
                ('reason_text', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AwardMst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_mst_text', models.CharField(max_length=20)),
                ('discription_text', models.CharField(max_length=100)),
            ],
        ),
    ]
